# Generated by Django 5.0.7 on 2024-07-26 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chai_images/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('ml', 'Masale Tea'), ('gr', 'Ginger Tea'), ('ki', 'Kiwi Tea'), ('pt', 'Plain Tea'), ('eh', 'Elachi Tea')], max_length=2)),
            ],
        ),
    ]
